package com.mycompany.abd3;


// Generated 2017-11-13 11:37:05 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cause generated by hbm2java
 */
public class Cause  implements java.io.Serializable {


     private BigDecimal causeId;
     private Issue issue;
     private String author;
     private Date date;
     private String content;
     private Set tasks = new HashSet(0);

    public Cause() {

    }

	
    public Cause(BigDecimal causeId) {
        this.causeId = causeId;
    }
    public Cause(BigDecimal causeId, Issue issue, String author, Date date, String content, Set tasks) {
       this.causeId = causeId;
       this.issue = issue;
       this.author = author;
       this.date = date;
       this.content = content;
       this.tasks = tasks;
    }
   
    public BigDecimal getCauseId() {
        return this.causeId;
    }
    
    public void setCauseId(BigDecimal causeId) {
        this.causeId = causeId;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Set getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }




}


