package com.mycompany.abd3;


// Generated 2017-11-13 11:37:05 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ClosingComment generated by hbm2java
 */
public class ClosingComment  implements java.io.Serializable {


     private BigDecimal closingCommentId;
     private Task task;
     private Issue issue;
     private String author;
     private Date date;
     private String content;

    public ClosingComment() {
    }

	
    public ClosingComment(BigDecimal closingCommentId) {
        this.closingCommentId = closingCommentId;
    }
    public ClosingComment(BigDecimal closingCommentId, Task task, Issue issue, String author, Date date, String content) {
       this.closingCommentId = closingCommentId;
       this.task = task;
       this.issue = issue;
       this.author = author;
       this.date = date;
       this.content = content;
    }
   
    public BigDecimal getClosingCommentId() {
        return this.closingCommentId;
    }
    
    public void setClosingCommentId(BigDecimal closingCommentId) {
        this.closingCommentId = closingCommentId;
    }
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


