package com.mycompany.abd3;


// Generated 2017-11-13 11:37:05 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Issue generated by hbm2java
 */
public class Issue  implements java.io.Serializable {


     private BigDecimal issueId;
     private String author;
     private Date date;
     private String coordinator;
     private String content;
     private Set tasks = new HashSet(0);
     private Set causes = new HashSet(0);
     private Set comments = new HashSet(0);
     private Set closingComments = new HashSet(0);

    public Issue() {
    }

	
    public Issue(BigDecimal issueId) {
        this.issueId = issueId;
    }
    public Issue(BigDecimal issueId, String author, Date date, String coordinator, String content, Set tasks, Set causes, Set comments, Set closingComments) {
       this.issueId = issueId;
       this.author = author;
       this.date = date;
       this.coordinator = coordinator;
       this.content = content;
       this.tasks = tasks;
       this.causes = causes;
       this.comments = comments;
       this.closingComments = closingComments;
    }
   
    public BigDecimal getIssueId() {
        return this.issueId;
    }
    
    public void setIssueId(BigDecimal issueId) {
        this.issueId = issueId;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getCoordinator() {
        return this.coordinator;
    }
    
    public void setCoordinator(String coordinator) {
        this.coordinator = coordinator;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Set getTasks() {
        return this.tasks;
    }
    
    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }
    public Set getCauses() {
        return this.causes;
    }
    
    public void setCauses(Set causes) {
        this.causes = causes;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getClosingComments() {
        return this.closingComments;
    }
    
    public void setClosingComments(Set closingComments) {
        this.closingComments = closingComments;
    }




}


