package com.mycompany.abd3;


// Generated 2017-11-13 11:37:05 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Task generated by hbm2java
 */
public class Task  implements java.io.Serializable {


     private BigDecimal taskId;
     private Cause cause;
     private Issue issue;
     private String author;
     private Date date;
     private String doer;
     private Date plan;
     private String content;
     private Set comments = new HashSet(0);
     private Set closingComments = new HashSet(0);

    public Task() {
    }

	
    public Task(BigDecimal taskId) {
        this.taskId = taskId;
    }
    public Task(BigDecimal taskId, Cause cause, Issue issue, String author, Date date, String doer, Date plan, String content, Set comments, Set closingComments) {
       this.taskId = taskId;
       this.cause = cause;
       this.issue = issue;
       this.author = author;
       this.date = date;
       this.doer = doer;
       this.plan = plan;
       this.content = content;
       this.comments = comments;
       this.closingComments = closingComments;
    }
   
    public BigDecimal getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(BigDecimal taskId) {
        this.taskId = taskId;
    }
    public Cause getCause() {
        return this.cause;
    }
    
    public void setCause(Cause cause) {
        this.cause = cause;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDoer() {
        return this.doer;
    }
    
    public void setDoer(String doer) {
        this.doer = doer;
    }
    public Date getPlan() {
        return this.plan;
    }
    
    public void setPlan(Date plan) {
        this.plan = plan;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getClosingComments() {
        return this.closingComments;
    }
    
    public void setClosingComments(Set closingComments) {
        this.closingComments = closingComments;
    }




}


